name: 🚀 Keep n8n Alive

on:
  schedule:
    # Каждые 2 минуты с 7:00 до 23:00
    - cron: '*/2 7-23 * * *'
    # Каждые 5 минут ночью  
    - cron: '*/5 0-6,23-23 * * *'
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  keep-n8n-warm:
    runs-on: ubuntu-latest
    steps:
      - name: 🔥 Light ping to keep n8n warm
        run: |
          echo "🕒 Pinging n8n at $(date)"
          RESPONSE=$(curl -s -w "HTTP_STATUS:%{http_code}" \
            "https://mlmotiv.app.n8n.cloud/webhook/data?ping=true")
          
          # Извлекаем HTTP статус
          HTTP_STATUS=$(echo "$RESPONSE" | grep -o 'HTTP_STATUS:[0-9]*' | cut -d':' -f2)
          BODY=$(echo "$RESPONSE" | sed 's/HTTP_STATUS:[0-9]*//g')
          
          echo "📡 Response: $BODY"
          echo "⚡ HTTP Status: $HTTP_STATUS"
          echo "✅ Ping completed at $(date)"
